// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: compliance.proto

// STREAM-LOCAL proto. This is intentionally NOT under the canonical proto/ tree.
// It declares the read-only compliance/audit RPCs that WS-K is adding to the
// canonical kseal API so this CLI stream can build a generated client and ship
// the commands ahead of the server. The CLI degrades gracefully: if the server
// does not implement an RPC (Connect code Unimplemented), the command reports
// "server capability unavailable" instead of failing. Once WS-K merges, the
// parent session repoints these commands at the canonical client and deletes
// this file.

package compliancepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuditTrailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // optional filter
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditTrailRequest) Reset() {
	*x = GetAuditTrailRequest{}
	mi := &file_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditTrailRequest) ProtoMessage() {}

func (x *GetAuditTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditTrailRequest.ProtoReflect.Descriptor instead.
func (*GetAuditTrailRequest) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuditTrailRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetAuditTrailRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAuditTrailRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAuditTrailRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// AuditEntry is one control-plane action. Time is a coarse bucket (no precise
// timestamps) and the actor is an operator/service principal, never an end user.
type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeBucket    int64                  `protobuf:"varint,2,opt,name=time_bucket,json=timeBucket,proto3" json:"time_bucket,omitempty"`
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetTimeBucket() int64 {
	if x != nil {
		return x.TimeBucket
	}
	return 0
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AuditEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type GetAuditTrailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditTrailResponse) Reset() {
	*x = GetAuditTrailResponse{}
	mi := &file_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditTrailResponse) ProtoMessage() {}

func (x *GetAuditTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditTrailResponse.ProtoReflect.Descriptor instead.
func (*GetAuditTrailResponse) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditTrailResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAuditTrailResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetKillSwitchStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // optional; empty = tenant-wide state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKillSwitchStateRequest) Reset() {
	*x = GetKillSwitchStateRequest{}
	mi := &file_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKillSwitchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKillSwitchStateRequest) ProtoMessage() {}

func (x *GetKillSwitchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKillSwitchStateRequest.ProtoReflect.Descriptor instead.
func (*GetKillSwitchStateRequest) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *GetKillSwitchStateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetKillSwitchStateRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetKillSwitchStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Engaged       bool                   `protobuf:"varint,3,opt,name=engaged,proto3" json:"engaged,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"` // tenant|app|build
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyHash    string                 `protobuf:"bytes,6,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	UpdatedBucket int64                  `protobuf:"varint,7,opt,name=updated_bucket,json=updatedBucket,proto3" json:"updated_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKillSwitchStateResponse) Reset() {
	*x = GetKillSwitchStateResponse{}
	mi := &file_compliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKillSwitchStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKillSwitchStateResponse) ProtoMessage() {}

func (x *GetKillSwitchStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKillSwitchStateResponse.ProtoReflect.Descriptor instead.
func (*GetKillSwitchStateResponse) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{4}
}

func (x *GetKillSwitchStateResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetKillSwitchStateResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetKillSwitchStateResponse) GetEngaged() bool {
	if x != nil {
		return x.Engaged
	}
	return false
}

func (x *GetKillSwitchStateResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetKillSwitchStateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetKillSwitchStateResponse) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *GetKillSwitchStateResponse) GetUpdatedBucket() int64 {
	if x != nil {
		return x.UpdatedBucket
	}
	return 0
}

type GetDataProcessingRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataProcessingRegistryRequest) Reset() {
	*x = GetDataProcessingRegistryRequest{}
	mi := &file_compliance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataProcessingRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataProcessingRegistryRequest) ProtoMessage() {}

func (x *GetDataProcessingRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataProcessingRegistryRequest.ProtoReflect.Descriptor instead.
func (*GetDataProcessingRegistryRequest) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataProcessingRegistryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ProcessingRecord is one record-of-processing-activities entry.
type ProcessingRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Purpose            string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	DataCategories     []string               `protobuf:"bytes,2,rep,name=data_categories,json=dataCategories,proto3" json:"data_categories,omitempty"`
	LegalBasis         string                 `protobuf:"bytes,3,opt,name=legal_basis,json=legalBasis,proto3" json:"legal_basis,omitempty"`
	Retention          string                 `protobuf:"bytes,4,opt,name=retention,proto3" json:"retention,omitempty"`
	Processors         []string               `protobuf:"bytes,5,rep,name=processors,proto3" json:"processors,omitempty"`
	EncryptedInTransit bool                   `protobuf:"varint,6,opt,name=encrypted_in_transit,json=encryptedInTransit,proto3" json:"encrypted_in_transit,omitempty"`
	EncryptedAtRest    bool                   `protobuf:"varint,7,opt,name=encrypted_at_rest,json=encryptedAtRest,proto3" json:"encrypted_at_rest,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessingRecord) Reset() {
	*x = ProcessingRecord{}
	mi := &file_compliance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingRecord) ProtoMessage() {}

func (x *ProcessingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingRecord.ProtoReflect.Descriptor instead.
func (*ProcessingRecord) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessingRecord) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ProcessingRecord) GetDataCategories() []string {
	if x != nil {
		return x.DataCategories
	}
	return nil
}

func (x *ProcessingRecord) GetLegalBasis() string {
	if x != nil {
		return x.LegalBasis
	}
	return ""
}

func (x *ProcessingRecord) GetRetention() string {
	if x != nil {
		return x.Retention
	}
	return ""
}

func (x *ProcessingRecord) GetProcessors() []string {
	if x != nil {
		return x.Processors
	}
	return nil
}

func (x *ProcessingRecord) GetEncryptedInTransit() bool {
	if x != nil {
		return x.EncryptedInTransit
	}
	return false
}

func (x *ProcessingRecord) GetEncryptedAtRest() bool {
	if x != nil {
		return x.EncryptedAtRest
	}
	return false
}

type GetDataProcessingRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Records       []*ProcessingRecord    `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataProcessingRegistryResponse) Reset() {
	*x = GetDataProcessingRegistryResponse{}
	mi := &file_compliance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataProcessingRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataProcessingRegistryResponse) ProtoMessage() {}

func (x *GetDataProcessingRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataProcessingRegistryResponse.ProtoReflect.Descriptor instead.
func (*GetDataProcessingRegistryResponse) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{7}
}

func (x *GetDataProcessingRegistryResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDataProcessingRegistryResponse) GetRecords() []*ProcessingRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_compliance_proto protoreflect.FileDescriptor

const file_compliance_proto_rawDesc = "" +
	"\n" +
	"\x10compliance.proto\x12\x18kseal.compliancelocal.v1\"\x86\x01\n" +
	"\x14GetAuditTrailRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x9b\x01\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtime_bucket\x18\x02 \x01(\x03R\n" +
	"timeBucket\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\"\x7f\n" +
	"\x15GetAuditTrailResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.kseal.compliancelocal.v1.AuditEntryR\aentries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"O\n" +
	"\x19GetKillSwitchStateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"\xe0\x01\n" +
	"\x1aGetKillSwitchStateResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x18\n" +
	"\aengaged\x18\x03 \x01(\bR\aengaged\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1f\n" +
	"\vpolicy_hash\x18\x06 \x01(\tR\n" +
	"policyHash\x12%\n" +
	"\x0eupdated_bucket\x18\a \x01(\x03R\rupdatedBucket\"?\n" +
	" GetDataProcessingRegistryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\x92\x02\n" +
	"\x10ProcessingRecord\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12'\n" +
	"\x0fdata_categories\x18\x02 \x03(\tR\x0edataCategories\x12\x1f\n" +
	"\vlegal_basis\x18\x03 \x01(\tR\n" +
	"legalBasis\x12\x1c\n" +
	"\tretention\x18\x04 \x01(\tR\tretention\x12\x1e\n" +
	"\n" +
	"processors\x18\x05 \x03(\tR\n" +
	"processors\x120\n" +
	"\x14encrypted_in_transit\x18\x06 \x01(\bR\x12encryptedInTransit\x12*\n" +
	"\x11encrypted_at_rest\x18\a \x01(\bR\x0fencryptedAtRest\"\x86\x01\n" +
	"!GetDataProcessingRegistryResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12D\n" +
	"\arecords\x18\x02 \x03(\v2*.kseal.compliancelocal.v1.ProcessingRecordR\arecords2\x9d\x03\n" +
	"\x11ComplianceService\x12p\n" +
	"\rGetAuditTrail\x12..kseal.compliancelocal.v1.GetAuditTrailRequest\x1a/.kseal.compliancelocal.v1.GetAuditTrailResponse\x12\x7f\n" +
	"\x12GetKillSwitchState\x123.kseal.compliancelocal.v1.GetKillSwitchStateRequest\x1a4.kseal.compliancelocal.v1.GetKillSwitchStateResponse\x12\x94\x01\n" +
	"\x19GetDataProcessingRegistry\x12:.kseal.compliancelocal.v1.GetDataProcessingRegistryRequest\x1a;.kseal.compliancelocal.v1.GetDataProcessingRegistryResponseBCZAgithub.com/kennguy3n/kseal/cli/internal/compliancepb;compliancepbb\x06proto3"

var (
	file_compliance_proto_rawDescOnce sync.Once
	file_compliance_proto_rawDescData []byte
)

func file_compliance_proto_rawDescGZIP() []byte {
	file_compliance_proto_rawDescOnce.Do(func() {
		file_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compliance_proto_rawDesc), len(file_compliance_proto_rawDesc)))
	})
	return file_compliance_proto_rawDescData
}

var file_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_compliance_proto_goTypes = []any{
	(*GetAuditTrailRequest)(nil),              // 0: kseal.compliancelocal.v1.GetAuditTrailRequest
	(*AuditEntry)(nil),                        // 1: kseal.compliancelocal.v1.AuditEntry
	(*GetAuditTrailResponse)(nil),             // 2: kseal.compliancelocal.v1.GetAuditTrailResponse
	(*GetKillSwitchStateRequest)(nil),         // 3: kseal.compliancelocal.v1.GetKillSwitchStateRequest
	(*GetKillSwitchStateResponse)(nil),        // 4: kseal.compliancelocal.v1.GetKillSwitchStateResponse
	(*GetDataProcessingRegistryRequest)(nil),  // 5: kseal.compliancelocal.v1.GetDataProcessingRegistryRequest
	(*ProcessingRecord)(nil),                  // 6: kseal.compliancelocal.v1.ProcessingRecord
	(*GetDataProcessingRegistryResponse)(nil), // 7: kseal.compliancelocal.v1.GetDataProcessingRegistryResponse
}
var file_compliance_proto_depIdxs = []int32{
	1, // 0: kseal.compliancelocal.v1.GetAuditTrailResponse.entries:type_name -> kseal.compliancelocal.v1.AuditEntry
	6, // 1: kseal.compliancelocal.v1.GetDataProcessingRegistryResponse.records:type_name -> kseal.compliancelocal.v1.ProcessingRecord
	0, // 2: kseal.compliancelocal.v1.ComplianceService.GetAuditTrail:input_type -> kseal.compliancelocal.v1.GetAuditTrailRequest
	3, // 3: kseal.compliancelocal.v1.ComplianceService.GetKillSwitchState:input_type -> kseal.compliancelocal.v1.GetKillSwitchStateRequest
	5, // 4: kseal.compliancelocal.v1.ComplianceService.GetDataProcessingRegistry:input_type -> kseal.compliancelocal.v1.GetDataProcessingRegistryRequest
	2, // 5: kseal.compliancelocal.v1.ComplianceService.GetAuditTrail:output_type -> kseal.compliancelocal.v1.GetAuditTrailResponse
	4, // 6: kseal.compliancelocal.v1.ComplianceService.GetKillSwitchState:output_type -> kseal.compliancelocal.v1.GetKillSwitchStateResponse
	7, // 7: kseal.compliancelocal.v1.ComplianceService.GetDataProcessingRegistry:output_type -> kseal.compliancelocal.v1.GetDataProcessingRegistryResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_compliance_proto_init() }
func file_compliance_proto_init() {
	if File_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compliance_proto_rawDesc), len(file_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compliance_proto_goTypes,
		DependencyIndexes: file_compliance_proto_depIdxs,
		MessageInfos:      file_compliance_proto_msgTypes,
	}.Build()
	File_compliance_proto = out.File
	file_compliance_proto_goTypes = nil
	file_compliance_proto_depIdxs = nil
}
