// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: compliance.proto

// STREAM-LOCAL proto. This is intentionally NOT under the canonical proto/ tree.
// It declares the read-only compliance/audit RPCs that WS-K is adding to the
// canonical kseal API so this CLI stream can build a generated client and ship
// the commands ahead of the server. The CLI degrades gracefully: if the server
// does not implement an RPC (Connect code Unimplemented), the command reports
// "server capability unavailable" instead of failing. Once WS-K merges, the
// parent session repoints these commands at the canonical client and deletes
// this file.
package compliancepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	compliancepb "github.com/kennguy3n/kseal/cli/internal/compliancepb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ComplianceServiceName is the fully-qualified name of the ComplianceService service.
	ComplianceServiceName = "kseal.compliancelocal.v1.ComplianceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ComplianceServiceGetAuditTrailProcedure is the fully-qualified name of the ComplianceService's
	// GetAuditTrail RPC.
	ComplianceServiceGetAuditTrailProcedure = "/kseal.compliancelocal.v1.ComplianceService/GetAuditTrail"
	// ComplianceServiceGetKillSwitchStateProcedure is the fully-qualified name of the
	// ComplianceService's GetKillSwitchState RPC.
	ComplianceServiceGetKillSwitchStateProcedure = "/kseal.compliancelocal.v1.ComplianceService/GetKillSwitchState"
	// ComplianceServiceGetDataProcessingRegistryProcedure is the fully-qualified name of the
	// ComplianceService's GetDataProcessingRegistry RPC.
	ComplianceServiceGetDataProcessingRegistryProcedure = "/kseal.compliancelocal.v1.ComplianceService/GetDataProcessingRegistry"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	complianceServiceServiceDescriptor                         = compliancepb.File_compliance_proto.Services().ByName("ComplianceService")
	complianceServiceGetAuditTrailMethodDescriptor             = complianceServiceServiceDescriptor.Methods().ByName("GetAuditTrail")
	complianceServiceGetKillSwitchStateMethodDescriptor        = complianceServiceServiceDescriptor.Methods().ByName("GetKillSwitchState")
	complianceServiceGetDataProcessingRegistryMethodDescriptor = complianceServiceServiceDescriptor.Methods().ByName("GetDataProcessingRegistry")
)

// ComplianceServiceClient is a client for the kseal.compliancelocal.v1.ComplianceService service.
type ComplianceServiceClient interface {
	// GetAuditTrail returns the tenant's operator audit entries (control-plane
	// actions). Entries carry no end-user PII.
	GetAuditTrail(context.Context, *connect.Request[compliancepb.GetAuditTrailRequest]) (*connect.Response[compliancepb.GetAuditTrailResponse], error)
	// GetKillSwitchState returns the current kill-switch / canary state for a
	// tenant (optionally narrowed to one app).
	GetKillSwitchState(context.Context, *connect.Request[compliancepb.GetKillSwitchStateRequest]) (*connect.Response[compliancepb.GetKillSwitchStateResponse], error)
	// GetDataProcessingRegistry returns the tenant's record-of-processing
	// entries (purpose, categories, legal basis, retention, processors).
	GetDataProcessingRegistry(context.Context, *connect.Request[compliancepb.GetDataProcessingRegistryRequest]) (*connect.Response[compliancepb.GetDataProcessingRegistryResponse], error)
}

// NewComplianceServiceClient constructs a client for the kseal.compliancelocal.v1.ComplianceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewComplianceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ComplianceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &complianceServiceClient{
		getAuditTrail: connect.NewClient[compliancepb.GetAuditTrailRequest, compliancepb.GetAuditTrailResponse](
			httpClient,
			baseURL+ComplianceServiceGetAuditTrailProcedure,
			connect.WithSchema(complianceServiceGetAuditTrailMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getKillSwitchState: connect.NewClient[compliancepb.GetKillSwitchStateRequest, compliancepb.GetKillSwitchStateResponse](
			httpClient,
			baseURL+ComplianceServiceGetKillSwitchStateProcedure,
			connect.WithSchema(complianceServiceGetKillSwitchStateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDataProcessingRegistry: connect.NewClient[compliancepb.GetDataProcessingRegistryRequest, compliancepb.GetDataProcessingRegistryResponse](
			httpClient,
			baseURL+ComplianceServiceGetDataProcessingRegistryProcedure,
			connect.WithSchema(complianceServiceGetDataProcessingRegistryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// complianceServiceClient implements ComplianceServiceClient.
type complianceServiceClient struct {
	getAuditTrail             *connect.Client[compliancepb.GetAuditTrailRequest, compliancepb.GetAuditTrailResponse]
	getKillSwitchState        *connect.Client[compliancepb.GetKillSwitchStateRequest, compliancepb.GetKillSwitchStateResponse]
	getDataProcessingRegistry *connect.Client[compliancepb.GetDataProcessingRegistryRequest, compliancepb.GetDataProcessingRegistryResponse]
}

// GetAuditTrail calls kseal.compliancelocal.v1.ComplianceService.GetAuditTrail.
func (c *complianceServiceClient) GetAuditTrail(ctx context.Context, req *connect.Request[compliancepb.GetAuditTrailRequest]) (*connect.Response[compliancepb.GetAuditTrailResponse], error) {
	return c.getAuditTrail.CallUnary(ctx, req)
}

// GetKillSwitchState calls kseal.compliancelocal.v1.ComplianceService.GetKillSwitchState.
func (c *complianceServiceClient) GetKillSwitchState(ctx context.Context, req *connect.Request[compliancepb.GetKillSwitchStateRequest]) (*connect.Response[compliancepb.GetKillSwitchStateResponse], error) {
	return c.getKillSwitchState.CallUnary(ctx, req)
}

// GetDataProcessingRegistry calls
// kseal.compliancelocal.v1.ComplianceService.GetDataProcessingRegistry.
func (c *complianceServiceClient) GetDataProcessingRegistry(ctx context.Context, req *connect.Request[compliancepb.GetDataProcessingRegistryRequest]) (*connect.Response[compliancepb.GetDataProcessingRegistryResponse], error) {
	return c.getDataProcessingRegistry.CallUnary(ctx, req)
}

// ComplianceServiceHandler is an implementation of the kseal.compliancelocal.v1.ComplianceService
// service.
type ComplianceServiceHandler interface {
	// GetAuditTrail returns the tenant's operator audit entries (control-plane
	// actions). Entries carry no end-user PII.
	GetAuditTrail(context.Context, *connect.Request[compliancepb.GetAuditTrailRequest]) (*connect.Response[compliancepb.GetAuditTrailResponse], error)
	// GetKillSwitchState returns the current kill-switch / canary state for a
	// tenant (optionally narrowed to one app).
	GetKillSwitchState(context.Context, *connect.Request[compliancepb.GetKillSwitchStateRequest]) (*connect.Response[compliancepb.GetKillSwitchStateResponse], error)
	// GetDataProcessingRegistry returns the tenant's record-of-processing
	// entries (purpose, categories, legal basis, retention, processors).
	GetDataProcessingRegistry(context.Context, *connect.Request[compliancepb.GetDataProcessingRegistryRequest]) (*connect.Response[compliancepb.GetDataProcessingRegistryResponse], error)
}

// NewComplianceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewComplianceServiceHandler(svc ComplianceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	complianceServiceGetAuditTrailHandler := connect.NewUnaryHandler(
		ComplianceServiceGetAuditTrailProcedure,
		svc.GetAuditTrail,
		connect.WithSchema(complianceServiceGetAuditTrailMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	complianceServiceGetKillSwitchStateHandler := connect.NewUnaryHandler(
		ComplianceServiceGetKillSwitchStateProcedure,
		svc.GetKillSwitchState,
		connect.WithSchema(complianceServiceGetKillSwitchStateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	complianceServiceGetDataProcessingRegistryHandler := connect.NewUnaryHandler(
		ComplianceServiceGetDataProcessingRegistryProcedure,
		svc.GetDataProcessingRegistry,
		connect.WithSchema(complianceServiceGetDataProcessingRegistryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/kseal.compliancelocal.v1.ComplianceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ComplianceServiceGetAuditTrailProcedure:
			complianceServiceGetAuditTrailHandler.ServeHTTP(w, r)
		case ComplianceServiceGetKillSwitchStateProcedure:
			complianceServiceGetKillSwitchStateHandler.ServeHTTP(w, r)
		case ComplianceServiceGetDataProcessingRegistryProcedure:
			complianceServiceGetDataProcessingRegistryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedComplianceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedComplianceServiceHandler struct{}

func (UnimplementedComplianceServiceHandler) GetAuditTrail(context.Context, *connect.Request[compliancepb.GetAuditTrailRequest]) (*connect.Response[compliancepb.GetAuditTrailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kseal.compliancelocal.v1.ComplianceService.GetAuditTrail is not implemented"))
}

func (UnimplementedComplianceServiceHandler) GetKillSwitchState(context.Context, *connect.Request[compliancepb.GetKillSwitchStateRequest]) (*connect.Response[compliancepb.GetKillSwitchStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kseal.compliancelocal.v1.ComplianceService.GetKillSwitchState is not implemented"))
}

func (UnimplementedComplianceServiceHandler) GetDataProcessingRegistry(context.Context, *connect.Request[compliancepb.GetDataProcessingRegistryRequest]) (*connect.Response[compliancepb.GetDataProcessingRegistryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kseal.compliancelocal.v1.ComplianceService.GetDataProcessingRegistry is not implemented"))
}
