org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

ksealStoreFile=../release_key.jks
ksealStorePassword=Elfoufou!23
ksealKeyAlias=key0
ksealKeyPassword=Elfoufou!23
ksealEndpoint=http://192.168.121.31:8080
ksealApiKey=ksk_8d1becb7160434c5_DnD4LR_RjortcQ-wfHMTTia2BHAbzyjm
ksealApp=279d536e-2ed9-4a25-9430-c067aa82f82d
ksealTenant=2c1aa4e7-d828-4680-b929-1d387af667e4
ksealGcpProject=0