#!/usr/bin/env bash
# Generate Go (protobuf + Connect) bindings from the kseal protobuf schemas.
#
# Requires: buf, protoc-gen-go, protoc-gen-connect-go on PATH
# (install with: make proto-tools).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

echo "==> buf lint"
buf lint

echo "==> buf generate (Go + Connect)"
buf generate

echo "==> done; Go bindings in server/gen, Rust prost generated by build.rs"
