{{- if and .Values.console.enabled .Values.console.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kseal.fullname" . }}-console
  labels:
    {{- include "kseal.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kseal.fullname" . }}-console
  minReplicas: {{ .Values.console.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.console.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.console.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
