{{- if and .Values.console.enabled .Values.console.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kseal.fullname" . }}-console
  labels:
    {{- include "kseal.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  minAvailable: {{ .Values.console.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "kseal.console.selectorLabels" . | nindent 6 }}
{{- end }}
