{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kseal.fullname" . }}
  labels:
    {{- include "kseal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kseal.fullname" . }}-server
                port:
                  number: {{ .Values.server.service.port }}
    {{- if .Values.console.enabled }}
    - host: {{ .Values.ingress.consoleHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kseal.fullname" . }}-console
                port:
                  number: {{ .Values.console.service.port }}
    {{- end }}
{{- end }}
