import Foundation

/// One sensitive string, hardened against a static `strings`/`nm` dump.
public struct HardenedString: Equatable {
    /// Stable identifier the host code uses to look the value up
    /// (e.g. `apiBaseURL`). Derived from the source key; never the secret.
    public let identifier: String
    /// Per-build, per-entry XOR key derived from the polymorphism seed.
    public let key: [UInt8]
    /// `plaintext XOR key`. The plaintext never appears in the binary.
    public let ciphertext: [UInt8]

    public init(identifier: String, key: [UInt8], ciphertext: [UInt8]) {
        self.identifier = identifier
        self.key = key
        self.ciphertext = ciphertext
    }
}

/// Transforms tenant-flagged string literals into per-build obfuscated form and
/// emits the Swift source that decodes them at runtime.
///
/// This is the App Store-safe core of string hardening: pure Swift codegen, no
/// private APIs, no dynamic code. After the transform, a `strings`/`nm` dump of
/// the compiled binary no longer reveals the plaintext; each build uses
/// different keys (driven by the polymorphism seed), so an extracted value or a
/// patched decoder does not transfer between builds.
///
/// The strength claim is deliberately honest (see the threat-model note in
/// ../../docs/build-hardening-ios.md): the XOR key is derived from a seed that
/// ships in the binary, so this *raises the cost* of static extraction and makes
/// bypasses decay per build — it is not unbreakable encryption. High-value
/// secrets must not live on the client at all; that is what server-side trust
/// and the request-proof model are for.
public struct StringHardener {
    public init() {}

    /// Domain separator so the string-hardening subkey is independent of any
    /// other seed-derived material.
    public static let subkeyContext = "kseal/string-hardening/v1"

    /// Hardens `entries` (identifier → plaintext) deterministically under `seed`.
    /// Output order is sorted by identifier for stable, reproducible codegen.
    public func harden(entries: [String: String], seed: PolymorphismSeed) -> [HardenedString] {
        let subkey = PolymorphismSeed(bytes: seed.keystream(length: 32, context: Self.subkeyContext))
        return entries.keys.sorted().map { identifier in
            let plaintext = Array((entries[identifier] ?? "").utf8)
            let key = subkey.keystream(length: max(plaintext.count, 1), context: "str:\(identifier)")
            var ciphertext = [UInt8](repeating: 0, count: plaintext.count)
            for i in 0..<plaintext.count {
                ciphertext[i] = plaintext[i] ^ key[i]
            }
            return HardenedString(identifier: identifier, key: Array(key.prefix(plaintext.count)), ciphertext: ciphertext)
        }
    }

    /// Round-trips a hardened entry back to plaintext (used by tests and tooling).
    public func reveal(_ hardened: HardenedString) -> String {
        var out = [UInt8](repeating: 0, count: hardened.ciphertext.count)
        for i in 0..<hardened.ciphertext.count {
            out[i] = hardened.ciphertext[i] ^ hardened.key[i]
        }
        return String(decoding: out, as: UTF8.self)
    }

    /// Generates the Swift source defining `enumName` with one static accessor
    /// per identifier plus a private XOR decoder. The file compiles into the
    /// target with no kseal runtime dependency.
    public func generateSwiftSource(_ hardened: [HardenedString], enumName: String = "KsealSecureStrings") -> String {
        var lines: [String] = []
        lines.append("// Generated by kseal-harden. DO NOT EDIT.")
        lines.append("//")
        lines.append("// Per-build obfuscated string table. Plaintext values are XOR-masked with")
        lines.append("// keys derived from this build's polymorphism seed and are recovered lazily")
        lines.append("// at first access. Regenerated every build; never commit.")
        lines.append("import Foundation")
        lines.append("")
        lines.append("enum \(enumName) {")
        lines.append("    private static func reveal(_ data: [UInt8], _ key: [UInt8]) -> String {")
        lines.append("        var out = [UInt8](repeating: 0, count: data.count)")
        lines.append("        for i in 0..<data.count { out[i] = data[i] ^ key[i] }")
        lines.append("        return String(decoding: out, as: UTF8.self)")
        lines.append("    }")
        lines.append("")
        var used: Set<String> = []
        for entry in hardened {
            // Disambiguate identifiers that sanitize to the same member so the
            // generated source never declares the same property twice.
            var member = Self.sanitizeIdentifier(entry.identifier)
            if used.contains(member) {
                var suffix = 2
                while used.contains("\(member)_\(suffix)") { suffix += 1 }
                member = "\(member)_\(suffix)"
            }
            used.insert(member)
            lines.append("    /// Hardened value for `\(entry.identifier)`.")
            lines.append("    static var \(Self.escapeKeyword(member)): String {")
            lines.append("        reveal(\(byteArrayLiteral(entry.ciphertext)), \(byteArrayLiteral(entry.key)))")
            lines.append("    }")
        }
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private func byteArrayLiteral(_ bytes: [UInt8]) -> String {
        "[" + bytes.map { String($0) }.joined(separator: ", ") + "]"
    }

    /// Maps an arbitrary identifier to a valid, collision-resistant Swift member.
    static func sanitizeIdentifier(_ raw: String) -> String {
        var result = ""
        for ch in raw.unicodeScalars {
            let isLetter = (ch >= "a" && ch <= "z") || (ch >= "A" && ch <= "Z") || ch == "_"
            let isDigit = ch >= "0" && ch <= "9"
            result.unicodeScalars.append(isLetter || isDigit ? ch : "_")
        }
        if result.isEmpty { result = "_" }
        if let first = result.unicodeScalars.first, first >= "0" && first <= "9" {
            result = "_" + result
        }
        return result
    }

    /// Swift reserved words that must be back-tick escaped when used as a member
    /// name (e.g. `class`, `return`, `import`).
    static let swiftKeywords: Set<String> = [
        "associatedtype", "borrowing", "class", "consuming", "deinit", "enum",
        "extension", "fileprivate", "func", "import", "init", "inout", "internal",
        "let", "open", "operator", "private", "precedencegroup", "protocol",
        "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
        "break", "case", "continue", "default", "defer", "do", "else",
        "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch",
        "where", "while", "as", "Any", "catch", "false", "is", "nil", "super",
        "self", "Self", "throw", "throws", "true", "try",
    ]

    /// Back-tick escapes `name` when it collides with a Swift keyword so the
    /// generated declaration compiles.
    static func escapeKeyword(_ name: String) -> String {
        swiftKeywords.contains(name) ? "`\(name)`" : name
    }
}
